name: Update GitHub Stats

on:
  push:
    branches:
      - main 

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README with Stats
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api?username=Vedanshu7&show_icons=true&count_private=true&include_all_commits=true&custom_title=Vedanshu's GitHub Stats&hide_border=true&bg_color=00000000&text_color=58a6ff&from=all-time&theme=dark&token=${{ secrets.PAT }}"
